### ISSUE TITLE
geom2graph failed to build on Ubuntu 22.04

### ISSUE THREAD

**Issue by Notgnoshi** [Notgnoshi/generative#124]
```
In file included from /home/nots/Documents/generative/tools/geom2graph/depends/googletest/googletest/include/gtest/internal/gtest-internal.h:65,
                 from /home/nots/Documents/generative/tools/geom2graph/depends/googletest/googletest/include/gtest/gtest.h:62,
                 from /home/nots/Documents/generative/tools/geom2graph/tests/geometry-noder-tests.cpp:10:
/home/nots/Documents/generative/tools/geom2graph/depends/googletest/googletest/include/gtest/gtest-message.h: In instantiation of ‘testing::Message& testing::Message::operator<<(const T&) [with T = std::unique_ptr<geos::geom::Geometry>]’:
/home/nots/Documents/generative/tools/geom2graph/tests/geometry-noder-tests.cpp:156:65:   required from here
/home/nots/Documents/generative/tools/geom2graph/depends/googletest/googletest/include/gtest/gtest-message.h:129:10: error: no match for ‘operator<<’ (operand types are ‘std::__cxx11::basic_stringstream<char>’ and ‘const std::unique_ptr<geos::geom::Geometry>’)
  129 |     *ss_ << val;
      |     ~~~~~^~~~~~


...


/usr/include/c++/11/ostream:750:5: error: no type named ‘type’ in ‘struct std::enable_if<false, void>’
In file included from /home/nots/Documents/generative/tools/geom2graph/depends/googletest/googletest/include/gtest/gtest.h:55,
                 from /home/nots/Documents/generative/tools/geom2graph/tests/geometry-noder-tests.cpp:10:
```
